# Generated by Django 3.2.6 on 2021-08-30 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StripePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=100)),
                ('billing_details', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.stripecustomer')),
            ],
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('latest_invoice_id', models.CharField(max_length=100)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.price')),
                ('stripe_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.stripepaymentmethod')),
            ],
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='stripe_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.stripesubscription'),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
